import tseslint from '@electron-toolkit/eslint-config-ts'
import eslintConfigPrettier from '@electron-toolkit/eslint-config-prettier'
import reactPlugin from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'

export default tseslint.config(
  // `coverage/` is generated by `npm run test:coverage` and gitignored. Without
  // it here, the second run of the commit gate fails lint on the report the
  // first run wrote.
  { ignores: ['**/node_modules/**', '**/dist/**', '**/out/**', '**/coverage/**'] },
  tseslint.configs.recommended,
  // Classic JSX runtime: this codebase imports React in every JSX file, so keep
  // react-in-jsx-scope / jsx-uses-react enabled (do NOT add the jsx-runtime
  // preset, which would flag those imports as unused).
  reactPlugin.configs.flat.recommended,
  reactHooks.configs['recommended-latest'],
  { settings: { react: { version: 'detect' } } },
  eslintConfigPrettier,
  // Node CJS scripts legitimately use require().
  { files: ['scripts/**'], rules: { '@typescript-eslint/no-require-imports': 'off' } },
  {
    rules: {
      // Return types are inferred throughout this app; requiring explicit
      // annotations is library-oriented noise that doesn't match the codebase.
      '@typescript-eslint/explicit-function-return-type': 'off',
      // TypeScript prop types supersede runtime PropTypes.
      'react/prop-types': 'off',
      // Raw apostrophes/quotes in JSX text render fine; escaping adds noise.
      'react/no-unescaped-entities': 'off',
      // Honour the intentional underscore-prefix "ignore me" convention.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }
      ],
      // Advisory, not blocking — adding deps blindly can change effect behaviour.
      'react-hooks/exhaustive-deps': 'warn'
    }
  }
)
