import '@fontsource/cinzel'
import '@fontsource/cinzel-decorative'
import '@fontsource/crimson-pro'

export { default as hybrasylTheme } from './hybrasyl'
export { default as chadulTheme } from './chadul'
export { default as danaanTheme } from './danaan'
export { default as grinnealTheme } from './grinneal'
export { default as mundanesTheme } from './mundanes'
export { default as dubhaimidTheme } from './dubhaimid'
